name = "ThermoFluids"
uuid = "37ca9b58-eb8e-4a54-8232-6afcfcfe2da6"
authors = ["Robert Walters"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
